style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/rantolin/bqsql
options:
  commits:
    # filters:
    #   Type:
    #     - feat
    #     - fix
    #     - perf
    #     - refactor
  commit_groups:
    title_maps:
      feat: Features
      fix: Bug Fixes
      perf: Performance Improvements
      refactor: Code Refactoring
      revert: Reverts
      docs: Documentation
      style: Styles
      test: Tests
      build: Build System
      ci: Continuous Integration
  header:
    pattern: "^(\\w*)(?:\\((.*)\\))?\\: (.*)$"
    pattern_maps:
      - Type
      - Scope
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE
